---
title: Magpie Wreathes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wreathes:
    title: Wreathes
    output: true
    permalink: "/wreathes/:path/"
defaults:
- scope:
    path: ''
    type: wreathes
  values:
    layout: wreath
    description:
    look_for:
    created_year:
    mainImage: 
baseurl: ''
permalink: pretty
